########################################################################
#
# File:   gpp.py
# Author: Mark Mitchell
# Date:   04/21/2003
#
# Contents:
#   Routines shared by G++ tests and resources.
#
# Copyright (c) 2003 by CodeSourcery, LLC.  All rights reserved. 
#
########################################################################

########################################################################
# Imports
########################################################################

from   compiler import Compiler, GPP
from   dejagnu_test import DejaGNUTest
import os
import re

########################################################################
# Variables
########################################################################

KIND_PREPROCESS = "preprocess"
KIND_COMPILE = "assembly"
KIND_ASSEMBLE = "object"
KIND_EXECUTABLE = "executable"
KIND_PRECOMPILE = "precompiled_header"

__compilation_mode_map = {
    KIND_PREPROCESS : Compiler.MODE_PREPROCESS,
    KIND_COMPILE : Compiler.MODE_COMPILE,
    KIND_ASSEMBLE : Compiler.MODE_ASSEMBLE,
    KIND_EXECUTABLE : Compiler.MODE_LINK,
    KIND_PRECOMPILE : GPP.MODE_PRECOMPILE,
    }
"""A map from DejaGNU compilation modes to 'Compiler' modes."""

__signal_regexp \
     = re.compile(".*cc: Internal compiler error: program.*got fatal "
		  "signal (6|11)")
"""A regular expression matching the output from a fatal signal."""

__newline_regexp = re.compile(r"[\r\n]")
"""A regular expression matching newline characters."""
	
########################################################################
# Functions
########################################################################

def compile(context, result, source_files, output_file, mode,
            options = [], test = None):
        """Compile the 'source_files'.

        'context' -- The 'Context' in which the test is running.
        
        'result' -- The QMTest 'Result' for the test or resource.
        
        'source_files' -- A list of paths giving the source files to be
        compiled.

        'output_file' -- The name of the output file to be created.

        'mode' -- One of the DejaGNU compilation modes.

        'options' -- A list of additional command-line options to be
        provided to the compiler.

        'test' -- The 'Test' object which is running, or 'None'.

        returns -- The output produced by the compiler."""

        # This method emulates g++_target_compile (in the GCC
        # testsuite), and target_compile (in the DejaGNU distribution).

        # There are a lot of complexities in default_target_compile
        # which we do not presently attempt to emulate.
        # Form the command-line.  Using Compiler.GetCompilationCommand
        # isn't guaranteed to create exactly the same command used by
        # DejaGNU, so we form the command manually.
        compiler = context["CompilerTable.compiler_table"]["cplusplus"]
        command = [compiler.GetPath()]
        # Add the global options (as originally specified in the
        # context file).  These are added before the options for this
        # test so that the latter can override the former.
        command += context["GPPInit.options"]
        command += options
        # Add the source files.
        mode = __compilation_mode_map[mode]
        if mode != Compiler.MODE_ASSEMBLE:
            command += source_files
        # Indicate the compilation mode.
        command += compiler._GetModeSwitches(mode)
        # For an executable test, provide necessary -L options.
        if mode == Compiler.MODE_LINK:
            command += map(lambda d: "-L" + d,
                           context["GPPInit.library_directories"])
        # Indicate where the output should go.
        command += ["-o", output_file]
        # Add the source files if they have not already been added.
        if mode == Compiler.MODE_ASSEMBLE:
            command += source_files

        # Run the compiler.
        if test:
            index = test._RecordCommand(result, command)
        status, output \
	   = compiler.ExecuteCommand(context.GetTemporaryDirectory(), command)
        if test:
            test._RecordCommandOutput(result, index, status, output)
                    
        # If there was no output, DejaGNU uses the exit status.
        if not output and status != 0:
            output = "exit statis is %d" % status

        return output


def check_compile(test, result, testcase, option, objname, gcc_output):
	"""Check the result of a compilation.

	'test' -- The QMTest 'Test' object.
	
	'result' -- The QMTest 'Result' object.
	
	'testcase' -- The name of the test.

	'option' -- The options used when performing the test.

	'objname' -- The name of the output file.

	'gcc_output' -- The output generated by the compiler.

	returns -- '1' if the compilation suceeded, '0' otherwise.  If
	'0' is returned, the 'result' has been updated to indicate the
	problem.
	
	This function emulates 'g++_check_compile' in
	'gcc-defs.exp'."""

	match = __signal_regexp.match(gcc_output)
	if match:
	    record_fail(test, result, testcase,
			"Got Signal %s, %s" % (match.group(1), option))
	    return 0

        gcc_output = __newline_regexp.sub(gcc_output, "")
		
        if gcc_output != "":
	    record_fail(test, result, testcase, option)
	    return 0
	    
	if objname and not os.path.exists(objname):
	    record_fail(test, result, testcase, option)
	    return 0

        record_pass(test, result, testcase, option)
	return 1
	

def record_pass(test, result, testcase, cflags):
	"""Emulate '${tool}_pass'.

	'test' -- The 'Test'.

	'result' -- The 'Result'.
	
	'testcase' -- The name of the test.

	'cflags' -- The options provided to the test."""

	if cflags:
	    message = "%s, %s" (testcase, cflags)
	else:
	    message = testcase
	test._RecordDejaGNUOutcome(result, DejaGNUTest.PASS, message)
		

def record_fail(test, result, testcase, cflags):
	"""Emulate '${tool}_fail'.

	'test' -- The 'Test'.

	'result' -- The 'Result'.
	
	'testcase' -- The name of the test.

	'cflags' -- The options provided to the test."""

	if cflags:
	    message = "%s, %s" (testcase, cflags)
	else:
	    message = testcase
	test._RecordDejaGNUOutcome(result, DejaGNUTest.FAIL, message)

	
def get_target_environment(context):
        """Return additional environment variables to set on the target.

        'context' -- The 'Context' in which this test is running.
        
        returns -- A map from strings (environment variable names) to
        strings (values for those variables).  These new variables are
        added to the environment when a program executes on the
        target."""
    
        env = {}
        dirs = ":".join(context["GPPInit.library_directories"])
        for v in ("LD_LIBRARY_PATH",
                  "SHLIB_PATH",
                  "LD_LIBRARY_N32_PATH",
                  "LD_LIBRARY64_PATH"):
            val = os.environ.get(v, "")
            if val:
                env[v] = val + ":" + dirs
            else:
                env[v] = dirs

        return env
        
        
